const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sounds=[
  {id:'mechanical',name:'机械钟摆',cat:'classic',type:'click'},{id:'wood',name:'木鱼',cat:'classic',type:'wood'},{id:'block',name:'木块',cat:'classic',type:'block'},{id:'digital',name:'电子滴答',cat:'classic',type:'digital'},
  {id:'kick',name:'底鼓',cat:'drum',type:'kick'},{id:'snare',name:'军鼓',cat:'drum',type:'snare'},{id:'hihat',name:'踩镲',cat:'drum',type:'hihat'},{id:'clap',name:'拍手',cat:'drum',type:'clap'},
  {id:'pizz',name:'弦乐拨奏',cat:'orchestra',type:'pizz'},{id:'timpani',name:'定音鼓',cat:'orchestra',type:'timpani'},{id:'baton',name:'指挥棒',cat:'orchestra',type:'baton'},
  {id:'softwood',name:'轻木块',cat:'soft',type:'softwood'},{id:'shaker',name:'沙锤',cat:'soft',type:'shaker'},{id:'bell',name:'柔和铃音',cat:'soft',type:'bell'}
];
const state={bpm:80,meter:4,subdivision:1,accent:true,bow:true,sound:'mechanical',volume:.72,playing:false,muted:false,currentBeat:0,currentSub:0,measure:0,nextNoteTime:0,timer:null,audio:null,training:false,startBpm:80};
const presets=[{name:'音阶慢练',bpm:60,meter:4,subdivision:1,sound:'wood'},{name:'快速分弓',bpm:120,meter:4,subdivision:2,sound:'block'},{name:'六八拍练习',bpm:72,meter:6,subdivision:1,sound:'pizz'}];

function ensureAudio(){if(!state.audio) state.audio=new (window.AudioContext||window.webkitAudioContext)(); if(state.audio.state==='suspended')state.audio.resume(); return state.audio}
function noiseBuffer(ctx,duration=.08){const b=ctx.createBuffer(1,ctx.sampleRate*duration,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function playTone(type,time,accent=false,preview=false){if(state.muted&&!preview)return;const ctx=ensureAudio(),out=ctx.createGain(),v=(preview?.5:state.volume)*(accent?1:.72);out.connect(ctx.destination);let osc,gain,src,filter;const env=(peak=v,end=.06)=>{gain=ctx.createGain();gain.gain.setValueAtTime(peak,time);gain.gain.exponentialRampToValueAtTime(.0001,time+end);gain.connect(out)};
  if(['snare','hihat','clap','shaker'].includes(type)){src=ctx.createBufferSource();src.buffer=noiseBuffer(ctx,type==='hihat'?.035:.1);filter=ctx.createBiquadFilter();filter.type=type==='snare'?'bandpass':'highpass';filter.frequency.value=type==='snare'?1700:type==='shaker'?4500:6500;env(v,type==='clap'?.12:.055);src.connect(filter);filter.connect(gain);src.start(time);return}
  osc=ctx.createOscillator();const cfg={click:['square',accent?1700:1250,.035],wood:['sine',accent?880:650,.07],block:['triangle',accent?1100:820,.055],digital:['square',accent?2100:1550,.035],kick:['sine',accent?115:85,.16],pizz:['triangle',accent?520:390,.11],timpani:['sine',accent?150:110,.22],baton:['square',accent?1350:980,.025],softwood:['sine',accent?650:500,.08],bell:['sine',accent?1200:900,.25]}[type]||['sine',800,.05];osc.type=cfg[0];osc.frequency.setValueAtTime(cfg[1],time);if(type==='kick'||type==='timpani')osc.frequency.exponentialRampToValueAtTime(cfg[1]*.55,time+cfg[2]);env(v,cfg[2]);osc.connect(gain);osc.start(time);osc.stop(time+cfg[2]+.02)
}
function scheduler(){while(state.nextNoteTime<state.audio.currentTime+.1){scheduleNote(state.nextNoteTime);advance()}state.timer=setTimeout(scheduler,25)}
function scheduleNote(time){const main=state.currentSub===0,beat=state.currentBeat,measure=state.measure,accent=main&&beat===0&&state.accent;if(main||state.subdivision>1)playTone(main?sounds.find(s=>s.id===state.sound).type:'softwood',time,accent);const delay=Math.max(0,(time-state.audio.currentTime)*1000);setTimeout(()=>visualTick(main,beat,measure),delay)}
function advance(){const seconds=60/state.bpm/state.subdivision;state.nextNoteTime+=seconds;state.currentSub++;if(state.currentSub>=state.subdivision){state.currentSub=0;state.currentBeat++;if(state.currentBeat>=state.meter){state.currentBeat=0;state.measure++;onMeasure()}}}
function visualTick(main,beat,measure){if(!main)return;const n=beat+1,bowDown=Math.floor(beat/2)%2===0;$('#beatCount').textContent=n;$('.beat-label').textContent=n===1?'重拍':'第 '+n+' 拍';$('#measureCount').textContent=`第 ${measure+1} 小节`;if(state.bow){$('#bowSymbol').textContent=bowDown?'▣':'∨';$('#bowStatus').textContent=`弓法：${bowDown?'下弓':'上弓'}`}const o=$('#beatOrbit');o.classList.remove('pulse');void o.offsetWidth;o.classList.add('pulse')}
function onMeasure(){if(state.training&&state.measure>0&&state.measure%num('#intervalMeasures')===0&&state.bpm<num('#targetBpm'))setBpm(Math.min(num('#targetBpm'),state.bpm+num('#stepBpm')));updateTraining()}
function start(){ensureAudio();state.playing=true;state.currentBeat=0;state.currentSub=0;state.nextNoteTime=state.audio.currentTime+.07;state.startBpm=state.bpm;$('#playIcon').textContent='Ⅱ';$('#playButton').classList.add('playing');$('#playButton').setAttribute('aria-label','暂停节拍器');scheduler()}
function stop(){state.playing=false;clearTimeout(state.timer);$('#playIcon').textContent='▶';$('#playButton').classList.remove('playing');$('#playButton').setAttribute('aria-label','开始节拍器');$('.beat-label').textContent='已暂停'}
function setBpm(v){state.bpm=Math.max(30,Math.min(240,Math.round(v)));$('#bpmInput').value=state.bpm;$('#bpmSlider').value=state.bpm;updateTraining()}
function num(s){return Number($(s).value)}
function updateStatus(){const sub={1:'四分音符',2:'八分音符',3:'三连音',4:'十六分音符'}[state.subdivision];$('#meterStatus').textContent=`${state.meter}/${state.meter===6?8:4} · ${sub}`}
function updateTraining(){const target=num('#targetBpm'),start=state.startBpm||state.bpm,p=Math.max(0,Math.min(100,(state.bpm-start)/(target-start||1)*100));$('#trainingProgress').style.width=p+'%';$('#trainingText').textContent=`${state.training?'进行中：':'开启后，'}每 ${num('#intervalMeasures')} 小节加速 ${num('#stepBpm')} BPM，直至 ${target} BPM。`}
function renderSounds(cat='all'){const box=$('#soundList');box.innerHTML='';sounds.filter(s=>cat==='all'||s.cat===cat).forEach(s=>{const b=document.createElement('button');b.className='sound-item'+(s.id===state.sound?' active':'');b.textContent=s.name;b.role='option';b.onclick=()=>{state.sound=s.id;renderSounds(cat);playTone(s.type,ensureAudio().currentTime,false,true)};box.append(b)})}
function allPresets(){return [...presets,...JSON.parse(localStorage.getItem('violin-presets')||'[]')]}
function renderPresets(){const box=$('#presetList');box.innerHTML='';allPresets().forEach(p=>{const b=document.createElement('button');b.className='preset';b.innerHTML=`${p.name}<small>${p.bpm} BPM · ${p.meter}/${p.meter===6?8:4}</small>`;b.onclick=()=>loadPreset(p);box.append(b)})}
function loadPreset(p){setBpm(p.bpm);state.meter=p.meter;state.subdivision=p.subdivision;state.sound=p.sound;$$('#meterChoices button').forEach(b=>b.classList.toggle('active',+b.dataset.value===state.meter));$('#subdivision').value=state.subdivision;updateStatus();renderSounds();toast('已载入 '+p.name)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
$('#playButton').onclick=()=>state.playing?stop():start();$('#minusBpm').onclick=()=>setBpm(state.bpm-1);$('#plusBpm').onclick=()=>setBpm(state.bpm+1);$('#bpmSlider').oninput=e=>setBpm(e.target.value);$('#bpmInput').onchange=e=>setBpm(e.target.value);
let taps=[];$('#tapTempo').onclick=()=>{const now=performance.now();taps=taps.filter(t=>now-t<2500);taps.push(now);if(taps.length>1){const gaps=taps.slice(1).map((t,i)=>t-taps[i]);setBpm(60000/(gaps.reduce((a,b)=>a+b)/gaps.length));$('#tapTempo').textContent=state.bpm+' BPM'}setTimeout(()=>$('#tapTempo').textContent='轻点测速',1800)};
$('#resetButton').onclick=()=>{if(state.playing)stop();state.measure=0;state.currentBeat=0;$('#measureCount').textContent='第 0 小节';$('#beatCount').textContent='1';$('.beat-label').textContent='准备';toast('已复位')};
$('#meterChoices').onclick=e=>{if(!e.target.dataset.value)return;state.meter=+e.target.dataset.value;$$('#meterChoices button').forEach(b=>b.classList.toggle('active',b===e.target));updateStatus()};$('#subdivision').onchange=e=>{state.subdivision=+e.target.value;updateStatus()};$('#accentToggle').onchange=e=>state.accent=e.target.checked;$('#bowToggle').onchange=e=>{state.bow=e.target.checked;$('#bowStatus').style.visibility=state.bow?'visible':'hidden';$('#bowSymbol').style.visibility=state.bow?'visible':'hidden'};
$('#soundTabs').onclick=e=>{if(!e.target.dataset.category)return;$$('#soundTabs button').forEach(b=>b.classList.toggle('active',b===e.target));renderSounds(e.target.dataset.category)};$('#previewSound').onclick=()=>playTone(sounds.find(s=>s.id===state.sound).type,ensureAudio().currentTime,false,true);$('#volumeSlider').oninput=e=>{state.volume=e.target.value/100;$('#volumeValue').textContent=e.target.value+'%'};
$('#soundToggle').onclick=()=>{state.muted=!state.muted;$('#soundToggle').textContent=state.muted?'×':'◖';toast(state.muted?'声音已关闭':'声音已开启')};$('#themeToggle').onclick=()=>document.body.classList.toggle('light');
$('#trainingToggle').onchange=e=>{state.training=e.target.checked;state.startBpm=state.bpm;updateTraining()};['#targetBpm','#stepBpm','#intervalMeasures'].forEach(s=>$(s).onchange=updateTraining);
$('#savePreset').onclick=()=>{const items=JSON.parse(localStorage.getItem('violin-presets')||'[]');items.push({name:'我的练习 '+(items.length+1),bpm:state.bpm,meter:state.meter,subdivision:state.subdivision,sound:state.sound});localStorage.setItem('violin-presets',JSON.stringify(items));renderPresets();toast('预设已保存')};
renderSounds();renderPresets();updateStatus();updateTraining();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
